sudo: require
sevices:
        - docker

before_install:
        - docker build -t build_image -f Dockerfile.dev .

script:
        -docker run -e CI=true build_image npm run test



                

